
---
apiVersion: v1
kind: Service
metadata:
  name: ianwood-test-redis-service
  labels:  
    username: ianwood
    env: test
spec:
  type: ClusterIP
  selector:
    app: ianwood-test-redis-deployment 
  ports:
  - name: ianwood-test-redis-service-rport
    port: 6379
    targetPort: 6379
