---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ianwood-test-redis-pvc
  labels: 
    username: ianwood
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
